# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  logging:

processors:
  batch:
  transform:
    metric_statements:
      - context: metric
        statements:
          # FIXME: remove this when this is issue is resolved: https://github.com/open-telemetry/opentelemetry-java/issues/4834
          - set(description, "") where name == "queueSize"
          # FIXME: remove this when the following 2 issues are resolved
          # Java: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9478
          # Go: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4301
          - set(description, "") where name == "rpc.server.duration"

connectors:
  spanmetrics:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [transform, batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
